### ISSUE TITLE
completion fails with ValueError

### ISSUE THREAD

**Issue by benatouba** [dcermak/salt-lsp#19]
Hi,
thx for your work on the server. I really appreciate it.

I am using the server with neovim. Unfortunately the completion does not properly work. Most of the time the log has the following errors:
```
ValueError: too many values to unpack (expected 2)
```
[salt-server.log](https://github.com/dcermak/salt-lsp/files/7227122/salt-server.log)

**Comment by dcermak** [comment]
Could you also upload the file that you were editing?

**Comment by benatouba** [comment]
I made a simple top.sls file and post the log here. There are multiple errors in the log. I am not sure which one messes up the completions.
[salt-server.log](https://github.com/dcermak/salt-lsp/files/7242056/salt-server.log)
```jinja2
base:
  '*':
    - pkg.installed:
```

**Comment by agraul** [comment]
Hi @benatouba,

is the code block the whole `top.sls` file you have? As far as I know you need two files, the `top.sls` which contains a mapping of minions to SLS files and (at least) one SLS file itself.

For example:
```yaml
# /srv/salt/top.sls
base:
  '*':                     # matches all minions
    - test                 # matches test.sls, assigned to all matched minions
```
```yaml
# /srv/salt/test.sls
vim:
  pkg.installed
```

Do you get the same error with a SLS file setup like I described?

**Comment by agraul** [comment]
I think both the `ValueError: too many values to unpack (expected 2)` and many of the `yaml.scanner.ScannerError` are fixed with #20

**Comment by dcermak** [comment]
@benatouba Could you recheck with the latest state from main?

**Comment by benatouba** [comment]
As it looks to me right now, the updates solved this issue. I still get no completion but that might have a different source. 

The log does only show "yaml.scan.errrors" with jinja templates (%). But that is not yet implemented, right?

**Comment by dcermak** [comment]
Benjamin Schmidt ***@***.***> writes:

> As it looks to me right now, the updates solved this issue. I still get no completion but that might have a different source. 
>
> The log does only show "yaml.scan.errrors" with jinja templates (%). But that is not yet implemented, right?

You are (unfortunately) correct, we did not get around to implement yaml
templates yet.

**Comment by benatouba** [comment]
Thx for the work so far. There still seem to be some problems with getting completion but I need to find out whether they might just be on my end.

**Comment by benatouba** [comment]
Now I get completion for submodules, some time after I open the file. It seems to take some time. Here is the log file for the test.sls suggested by @agraul . As you can see there are no errors in the log. Maybe there is still helpful stuff for you in there.
[salt-server.log](https://github.com/dcermak/salt-lsp/files/7505107/salt-server.log)
